require("dotenv").config();
const express = require("express");
const cors = require("cors");
const path = require("path");
const mongoose = require("./db/conn");
const roleRoute = require("./routes/roleRoutes");
const userRoute = require("./routes/userRoutes");
const pageGroupRoute = require("./routes/pagesGroupRoutes");
const pagesRoute = require("./routes/pagesRoutes");
const pageElemntRoute = require("./routes/pagesElementRoutes");
const documentRoute = require("./routes/documentRoutes");
const userprofileroute = require("./routes/userProfileRoutes");
const permissionRoute = require("./routes/permissionRoutes");
const professionalInfoRoute = require("./routes/professionalinfoRoutes");
const worktyprequestRoute = require("./routes/workTypeRequesRoutes");
const shiftRequestRoute = require("./routes/shiftRequestRoutes");
const rotatingShiftRoute = require("./routes/rotatingShiftRoutes");
const contactRoute = require("./routes/contactRoutes");
const documentTemplateRoute = require("./routes/documentTemplateRoute");
const documentSubmissionRoute = require("./routes/documentSubmissionRoute");
const documentRequestRoute = require("./routes/documentRRoute");
const documentCategoryRoute = require("./routes/documentcRoute");
// const employeeRoute = require("./routes/employeeRoutes");
const employmentRoute = require("./routes/employmentRoutes");
const organizationRoute = require("./routes/organizationRoutes");
const emailRoute = require("./routes/emailRoutes");
const rolePermissionRoute = require("./routes/rolePermissionRoutes");
const bankRoute = require("./routes/bankdetailsRoutes");
const worktypeAssignRoute = require("./routes/workTypeAssignmentRoutes");
const leaveRoute = require("./routes/leaveRoutes");
const leaveAllocationRoute =require("./routes/leaveAllocationRoutes");
const leaveTypeRoute = require("./routes/leaveTypeRoutes");
const roleDocumentRoute = require("./routes/roleDocumentRoutes");
const orgDocumentRoute=require("./routes/orgDocumentRoutes")
const holidayRoutes = require("./routes/holidayRoutes");
const teamDocumentRoutes =require("./routes/teamDocumentRoutes")
const payrollRoute = require("./routes/payrollRoutes");
const employeePayrollRoute = require("./routes/employeePayrollRoutes");
const PORT = process.env.PORT || 6010;
const app = express();

app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
console.log('Serving uploads from:', path.join(__dirname, "my-upload/uploads"));
app.use("/uploads", express.static(path.join(__dirname, "my-upload/uploads")));
app.use("/roles", roleRoute);
app.use("/permissions", permissionRoute);
app.use("/role-permissions", rolePermissionRoute);
app.use("/user", userRoute);
app.use("/page-group", pageGroupRoute);
app.use("/pages", pagesRoute);
app.use("/pageelement", pageElemntRoute);
app.use("/api", documentRoute);
app.use("/api", professionalInfoRoute);
app.use("/api", userprofileroute);
app.use("/api", worktyprequestRoute);
app.use("/api", worktypeAssignRoute);
app.use("/api", shiftRequestRoute);
app.use("/api", rotatingShiftRoute);
app.use("/api/emp", employmentRoute);
app.use("/documents/v1", documentCategoryRoute);
app.use("/documents/v1", documentRequestRoute);
app.use("/documentsubmission/v1", documentSubmissionRoute);
app.use("/documents/v1", documentRoute);
app.use("/documents/v1", roleDocumentRoute);
app.use("/documents/v1/org-doc", orgDocumentRoute);
app.use("/documents/v1/team-doc", teamDocumentRoutes);
app.use("/documents-template/v1", documentTemplateRoute);
app.use("/organization",organizationRoute);
app.use("/email",emailRoute);
app.use('/bank',bankRoute);
app.use('/contact',contactRoute);
app.use("/leave", leaveRoute);
app.use("/allocation",leaveAllocationRoute);
app.use("/leaveType",leaveTypeRoute);
app.use("/api/leave", leaveRoute);
app.use("/api/v1/holidays", holidayRoutes);
app.use("/payroll", payrollRoute);
app.use("/employee-payroll", employeePayrollRoute);
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: "Something went wrong!" });
});

mongoose.connection.once("open", () => {
  app.listen(PORT, () => {
    console.log(`Server up and down ${PORT}`);
  });
});
